DUREE_TOTALE_SECONDES = 10000
SECONDES_PAR_MINUTE = 60
MINUTES_PAR_HEURE = 60
SECONDES_PAR_HEURE = SECONDES_PAR_MINUTE * MINUTES_PAR_HEURE

nb_heures = DUREE_TOTALE_SECONDES // SECONDES_PAR_MINUTE // MINUTES_PAR_HEURE     # int
print(nb_heures)
nb_minutes = DUREE_TOTALE_SECONDES % SECONDES_PAR_HEURE // MINUTES_PAR_HEURE   # int, entre 0 et 59
print(nb_minutes)
#nb_secondes =  # int, entre 0 et 59